#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#monitores y configuracion
bspc monitor -d 1 2 3 4 5 6


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#reglas de ventanas y programas
bspc rule -a Brave-browser desktop='^1' flollow=on
bspc rule -a Firefox desktop='^6' flollow=on
bspc rule -a discord desktop='^8' flollow=on state=floating
#state=floating follow=on
bspc rule -a Code desktop='^3' flollow=on
bspc rule -a Caja desktop='^4' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#seguimiento de raton en ventanas

bspc config focus_follows_pointer true

#fundo de pantalla

feh --bg-fill ~/Desktop/fondos/1145320.png

#polybar con el tema forest

~/.config/polybar/forest/launch.sh

#lanzamiento de picom, esto nos pone la trasparencia

picom --experimental-backends &
bspc config border_width 2
